- name: Upgrade all S.O packages
  yum:
    name: '*'
    state: latest
- name: Install Git Client
  yum:  
    name:  git 
    state: latest
- name: Settings hosts lab ansible 
  lineinfile: 
    dest: /etc/hosts
    state: present 
    line: "{{item}}"
  with_items:
    - 192.168.10.2 control-node
    - 192.168.10.3 app01
    - 192.168.10.4 db01