#/bin/sh

cat <<  EOT >> /home/vagrant/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDH5akakWwuy29p9ZSGjMC/jdJEZIM6i1bpNYuJGibRq1AAN6YBaPtnBVGhV1yVy9s8ivz8wXvl8T2Df6yIgWdg2yybUTzZNwAcep8PJ5TmMlu0Jag4rCPOqmC1DGOCEf+InNNf1+tatcj+KMXBWSfHlSOwGfwPVOn54lOMXnhOn2x6bvbQKLK0EYvPtZMmyqBk/SK4wES3ZrN4SMiiRxIqLQDzY/R8tE+KSCkVpXVtmrmDBBV5VKJKEK81Hm0vInchk+dQ6hdLDanMhv+UyRgdkTWb9yCShiHwjGsPB4Ob0Ash7GbIHENd8RjliC+Hene6zORBYQlrVFcaSzjgQHxH vagrant@control-node
EOT